### ISSUE TITLE
Semaine 1

### ISSUE THREAD

**Issue by denissteffen** [denissteffen/Ex#1]
J'ai corrigé quelques trucs typographiques et j'ai fait des essais numériques.
J'ai juste un doute par rapport à un test : 
<img width="1440" alt="capture d ecran 2018-02-26 a 19 44 56" src="https://user-images.githubusercontent.com/25927712/36688723-92a42b02-1b2d-11e8-9aa1-863a5ab26ea2.png">

**Comment by gbossy** [comment]
Il y a pas de problèmes, c'est juste qu'on lit ou affiche les nombres dans le mauvais sens.

**Comment by denissteffen** [comment]
Okay je me disais aussi mdr
