### ISSUE TITLE
Week 4 fermé

### ISSUE THREAD

**Issue by denissteffen** [denissteffen/Ex#2]
Au fait, on a prouvé comment que cone(X~) est fermé? 
Il faudrait pas dire que puisque cone(X~) est un polyhedron de vecteurs de X~ lin ind, alors c'est un ensemble de solutions du LP et donc une intersection de half spaces (qui sont fermés) et donc par un exo des semaines précédentes il est convexe et fermé?

**Comment by denissteffen** [comment]
Et je pense qu'il faudrait aussi prouver que 
![w4](https://user-images.githubusercontent.com/25927712/37520926-2719c1ee-291f-11e8-8f50-2e5400c8ea46.jpg)

**Comment by gbossy** [comment]
Cette preuve est triviale on l'a faite en exo. Comme pour tout x dans cone(X) il existe un X tilde tq x est dans cone(Xtilde), gauche est dans droite. et comme x tilode est dans X, cone(Xtilde) est dans cone(X).
Cone(X~) fermé car le produit scalaire avec a_i^-1 est une app cont et on fait la préimage d'un fermé.

**Comment by denissteffen** [comment]
ok oui mais il faut bien l'écrire ;-)
